package org.example

fun main() {

    val bayernMunich = Equipo("Bayern Múnich", "Alemania")
    val borussiaDortmund = Equipo("Borussia Dortmund", "Alemania")
    val bayerLeverkusen = Equipo("Bayer 04 Leverkusen", "Alemania")
    val rbLeipzig = Equipo("RB Leipzig", "Alemania")
    val borussiaMonchengladbach = Equipo("Borussia Mönchengladbach", "Alemania")
    val eintrachtFrankfurt = Equipo("Eintracht Frankfurt", "Alemania")
    val vflWolfsburgo = Equipo("VfL Wolfsburgo", "Alemania")
    val vfbStuttgart = Equipo("VfB Stuttgart", "Alemania")
    val tsgHoffenheim = Equipo("TSG 1899 Hoffenheim", "Alemania")
    val fcKoln = Equipo("FC Colonia", "Alemania")
    val werderBremen = Equipo("Werder Bremen", "Alemania")
    val fcAugsburg = Equipo("FC Augsburgo", "Alemania")
    val mainz05 = Equipo("Mainz 05", "Alemania")
    val unionBerlin = Equipo("Union Berlin", "Alemania")
    val scFreiburg = Equipo("SC Friburgo", "Alemania")
    val hamburgosv = Equipo("Hamburgo SV", "Alemania")
    val bochum = Equipo("Bochum", "Alemania")
    val stPauli = Equipo("FC St. Pauli", "Alemania")

    // BAYERN MÚNICH (4-2-3-1)
    val neuer = Jugador("Manuel Neuer", Posicion.ARQUERO, Habilidades(90, 85, 65))
    val davies = Jugador("Alphonso Davies", Posicion.DEFENSOR, Habilidades(82, 83, 94))
    val deLigt = Jugador("Matthijs de Ligt", Posicion.DEFENSOR, Habilidades(87, 82, 75))
    val kim = Jugador("Kim Min-jae", Posicion.DEFENSOR, Habilidades(86, 79, 76))
    val mazraoui = Jugador("Noussair Mazraoui", Posicion.DEFENSOR, Habilidades(83, 81, 80))
    val kimmich = Jugador("Joshua Kimmich", Posicion.MEDIOCAMPISTA, Habilidades(88, 90, 79))
    val goretzka = Jugador("Leon Goretzka", Posicion.MEDIOCAMPISTA, Habilidades(85, 86, 78))
    val sane = Jugador("Leroy Sané", Posicion.DELANTERO, Habilidades(86, 84, 93))
    val musiala = Jugador("Jamal Musiala", Posicion.MEDIOCAMPISTA, Habilidades(89, 91, 87))
    val coman = Jugador("Kingsley Coman", Posicion.DELANTERO, Habilidades(84, 81, 91))
    val kane = Jugador("Harry Kane", Posicion.DELANTERO, Habilidades(92, 88, 82))

// BORUSSIA DORTMUND (4-3-3)
    val kobel = Jugador("Gregor Kobel", Posicion.ARQUERO, Habilidades(88, 76, 72))
    val ryerson = Jugador("Julian Ryerson", Posicion.DEFENSOR, Habilidades(82, 79, 81))
    val schlotterbeck = Jugador("Nico Schlotterbeck", Posicion.DEFENSOR, Habilidades(85, 81, 77))
    val hummels = Jugador("Mats Hummels", Posicion.DEFENSOR, Habilidades(86, 83, 68))
    val maatsen = Jugador("Ian Maatsen", Posicion.DEFENSOR, Habilidades(81, 78, 85))
    val can = Jugador("Emre Can", Posicion.MEDIOCAMPISTA, Habilidades(83, 85, 76))
    val brandt = Jugador("Julian Brandt", Posicion.MEDIOCAMPISTA, Habilidades(86, 88, 84))
    val reus = Jugador("Marco Reus", Posicion.MEDIOCAMPISTA, Habilidades(87, 89, 82))
    val malen = Jugador("Donyell Malen", Posicion.DELANTERO, Habilidades(84, 80, 89))
    val moukoko = Jugador("Youssoufa Moukoko", Posicion.DELANTERO, Habilidades(85, 78, 86))
    val adeyemi = Jugador("Karim Adeyemi", Posicion.DELANTERO, Habilidades(83, 79, 92))

// BAYER LEVERKUSEN (3-4-2-1)
    val hradecky = Jugador("Lukáš Hrádecký", Posicion.ARQUERO, Habilidades(85, 74, 70))
    val tah = Jugador("Jonathan Tah", Posicion.DEFENSOR, Habilidades(85, 78, 74))
    val tapsoba = Jugador("Edmond Tapsoba", Posicion.DEFENSOR, Habilidades(84, 77, 76))
    val hincapie = Jugador("Piero Hincapié", Posicion.DEFENSOR, Habilidades(83, 79, 81))
    val frimpong = Jugador("Jeremie Frimpong", Posicion.DEFENSOR, Habilidades(82, 80, 93))
    val xhaka = Jugador("Granit Xhaka", Posicion.MEDIOCAMPISTA, Habilidades(86, 88, 72))
    val palacios = Jugador("Exequiel Palacios", Posicion.MEDIOCAMPISTA, Habilidades(84, 87, 78))
    val grimaldo = Jugador("Álex Grimaldo", Posicion.DEFENSOR, Habilidades(84, 86, 82))
    val hofmann = Jugador("Jonas Hofmann", Posicion.MEDIOCAMPISTA, Habilidades(83, 85, 84))
    val wirtz = Jugador("Florian Wirtz", Posicion.MEDIOCAMPISTA, Habilidades(90, 92, 85))
    val boniface = Jugador("Victor Boniface", Posicion.DELANTERO, Habilidades(86, 82, 84))

// RB LEIPZIG (4-4-2)
    val gulacsi = Jugador("Péter Gulácsi", Posicion.ARQUERO, Habilidades(84, 73, 68))
    val henrichs = Jugador("Benjamin Henrichs", Posicion.DEFENSOR, Habilidades(83, 81, 79))
    val lukeba = Jugador("Castello Lukeba", Posicion.DEFENSOR, Habilidades(82, 78, 77))
    val simakan = Jugador("Mohamed Simakan", Posicion.DEFENSOR, Habilidades(83, 79, 81))
    val raum = Jugador("David Raum", Posicion.DEFENSOR, Habilidades(82, 84, 83))
    val schlager = Jugador("Xaver Schlager", Posicion.MEDIOCAMPISTA, Habilidades(84, 86, 80))
    val kampl = Jugador("Kevin Kampl", Posicion.MEDIOCAMPISTA, Habilidades(83, 85, 76))
    val olmo = Jugador("Dani Olmo", Posicion.MEDIOCAMPISTA, Habilidades(87, 89, 85))
    val simons = Jugador("Xavi Simons", Posicion.MEDIOCAMPISTA, Habilidades(85, 87, 86))
    val sesko = Jugador("Benjamin Šeško", Posicion.DELANTERO, Habilidades(84, 79, 82))
    val openda = Jugador("Lois Openda", Posicion.DELANTERO, Habilidades(86, 81, 88))

    // BORUSSIA MÖNCHENGLADBACH (4-2-3-1)
    val olschowsky = Jugador("Jan Olschowsky", Posicion.ARQUERO, Habilidades(78, 65, 62))
    val scally = Jugador("Joe Scally", Posicion.DEFENSOR, Habilidades(79, 75, 82))
    val mommel = Jugador("Ko Itakura", Posicion.DEFENSOR, Habilidades(82, 78, 76))
    val friedrich = Jugador("Marvin Friedrich", Posicion.DEFENSOR, Habilidades(81, 77, 72))
    val netz = Jugador("Luca Netz", Posicion.DEFENSOR, Habilidades(77, 79, 81))
    val kone = Jugador("Manu Koné", Posicion.MEDIOCAMPISTA, Habilidades(82, 84, 79))
    val weigl = Jugador("Julian Weigl", Posicion.MEDIOCAMPISTA, Habilidades(83, 85, 76))
    val honorat = Jugador("Franck Honorat", Posicion.DELANTERO, Habilidades(81, 78, 86))
    val neuhaus = Jugador("Florian Neuhaus", Posicion.MEDIOCAMPISTA, Habilidades(82, 83, 80))
    val ngoumou = Jugador("Nathan Ngoumou", Posicion.DELANTERO, Habilidades(79, 74, 88))
    val plea = Jugador("Alassane Pléa", Posicion.DELANTERO, Habilidades(83, 81, 82))

// EINTRACHT FRANKFURT (3-4-3)
    val trapp = Jugador("Kevin Trapp", Posicion.ARQUERO, Habilidades(84, 72, 74))
    val tuta = Jugador("Tuta", Posicion.DEFENSOR, Habilidades(82, 76, 79))
    val koch = Jugador("Robin Koch", Posicion.DEFENSOR, Habilidades(83, 78, 75))
    val pacho = Jugador("Willian Pacho", Posicion.DEFENSOR, Habilidades(81, 77, 73))
    val buta = Jugador("Aurélio Buta", Posicion.DEFENSOR, Habilidades(79, 78, 84))
    val skhiri = Jugador("Ellyes Skhiri", Posicion.MEDIOCAMPISTA, Habilidades(84, 83, 76))
    val dinaebi = Jugador("Donny van de Beek", Posicion.MEDIOCAMPISTA, Habilidades(82, 84, 78))
    val max = Jugador("Philipp Max", Posicion.DEFENSOR, Habilidades(80, 82, 77))
    val chaibi = Jugador("Farès Chaïbi", Posicion.MEDIOCAMPISTA, Habilidades(81, 83, 82))
    val marmoush = Jugador("Omar Marmoush", Posicion.DELANTERO, Habilidades(83, 79, 86))
    val kalajdzic = Jugador("Sasa Kalajdzic", Posicion.DELANTERO, Habilidades(82, 78, 72))

// VFB STUTTGART (4-3-3)
    val nubel = Jugador("Alexander Nübel", Posicion.ARQUERO, Habilidades(83, 74, 71))
    val vagnoman = Jugador("Josha Vagnoman", Posicion.DEFENSOR, Habilidades(80, 76, 82))
    val anton = Jugador("Waldemar Anton", Posicion.DEFENSOR, Habilidades(83, 78, 75))
    val zagadou = Jugador("Dan-Axel Zagadou", Posicion.DEFENSOR, Habilidades(81, 77, 72))
    val mittelstadt = Jugador("Maximilian Mittelstädt", Posicion.DEFENSOR, Habilidades(79, 80, 81))
    val karazor = Jugador("Atakan Karazor", Posicion.MEDIOCAMPISTA, Habilidades(80, 82, 76))
    val stiller = Jugador("Angelo Stiller", Posicion.MEDIOCAMPISTA, Habilidades(82, 84, 78))
    val lewicki = Jugador("Lukas Lewicki", Posicion.MEDIOCAMPISTA, Habilidades(81, 83, 79))
    val silas = Jugador("Silas Katompa Mvumpa", Posicion.DELANTERO, Habilidades(82, 77, 88))
    val undav = Jugador("Deniz Undav", Posicion.DELANTERO, Habilidades(84, 80, 82))
    val guirassy = Jugador("Serhou Guirassy", Posicion.DELANTERO, Habilidades(85, 82, 78))

// VFL WOLFSBURGO (4-4-2)
    val casteels = Jugador("Koen Casteels", Posicion.ARQUERO, Habilidades(83, 73, 69))
    val baku = Jugador("Ridle Baku", Posicion.DEFENSOR, Habilidades(81, 78, 84))
    val lacroix = Jugador("Maxence Lacroix", Posicion.DEFENSOR, Habilidades(83, 77, 82))
    val jenz = Jugador("Moritz Jenz", Posicion.DEFENSOR, Habilidades(80, 76, 75))
    val maehle = Jugador("Joakim Mæhle", Posicion.DEFENSOR, Habilidades(79, 77, 83))
    val svanberg = Jugador("Mattias Svanberg", Posicion.MEDIOCAMPISTA, Habilidades(82, 83, 79))
    val arnold = Jugador("Maximilian Arnold", Posicion.MEDIOCAMPISTA, Habilidades(84, 85, 76))
    val wimmer = Jugador("Patrick Wimmer", Posicion.MEDIOCAMPISTA, Habilidades(81, 79, 85))
    val majer = Jugador("Lovro Majer", Posicion.MEDIOCAMPISTA, Habilidades(83, 84, 80))
    val wind = Jugador("Jonas Wind", Posicion.DELANTERO, Habilidades(84, 81, 78))
    val amine = Jugador("Amine Adli", Posicion.DELANTERO, Habilidades(82, 78, 86))

    // TSG HOFFENHEIM (4-3-3)
    val baumann = Jugador("Oliver Baumann", Posicion.ARQUERO, Habilidades(83, 72, 68))
    val vogt = Jugador("Kevin Vogt", Posicion.DEFENSOR, Habilidades(81, 77, 73))
    val brooks = Jugador("John Brooks", Posicion.DEFENSOR, Habilidades(82, 76, 71))
    val akpoguma = Jugador("Kevin Akpoguma", Posicion.DEFENSOR, Habilidades(79, 75, 78))
    val kaderabek = Jugador("Pavel Kadeřábek", Posicion.DEFENSOR, Habilidades(78, 74, 80))
    val promel = Jugador(" Grischa Prömel", Posicion.MEDIOCAMPISTA, Habilidades(82, 83, 76))
    val stach = Jugador("Anton Stach", Posicion.MEDIOCAMPISTA, Habilidades(81, 82, 75))
    val bebbou = Jugador("Ihlas Bebou", Posicion.DELANTERO, Habilidades(80, 76, 86))
    val kramaric = Jugador("Andrej Kramarić", Posicion.DELANTERO, Habilidades(84, 82, 79))
    val weghorst = Jugador("Wout Weghorst", Posicion.DELANTERO, Habilidades(82, 80, 72))
    val berisha = Jugador("Vedad Ibišević", Posicion.DELANTERO, Habilidades(79, 77, 81))

// FC COLONIA (4-2-3-1)
    val schwabe = Jugador("Marvin Schwäbe", Posicion.ARQUERO, Habilidades(81, 70, 66))
    val carstensen = Jugador("Lennard Carstensen", Posicion.DEFENSOR, Habilidades(77, 73, 79))
    val hubers = Jugador("Julian Chabot", Posicion.DEFENSOR, Habilidades(79, 75, 72))
    val heintz = Jugador("Dominique Heintz", Posicion.DEFENSOR, Habilidades(78, 74, 71))
    val paqarada = Jugador("Leart Paqarada", Posicion.DEFENSOR, Habilidades(76, 78, 77))
    val martel = Jugador("Eric Martel", Posicion.MEDIOCAMPISTA, Habilidades(79, 80, 75))
    val ljubicic = Jugador("Ellyes Skhiri", Posicion.MEDIOCAMPISTA, Habilidades(82, 81, 74))
    val maina = Jugador("Jan Thielmann", Posicion.DELANTERO, Habilidades(78, 76, 84))
    val kainz = Jugador("Florian Kainz", Posicion.MEDIOCAMPISTA, Habilidades(80, 82, 78))
    val alidou = Jugador("Faride Alidou", Posicion.DELANTERO, Habilidades(77, 74, 83))
    val selke = Jugador("Davie Selke", Posicion.DELANTERO, Habilidades(79, 75, 76))

// WERDER BREMEN (4-4-2)
    val zetterer = Jugador("Michael Zetterer", Posicion.ARQUERO, Habilidades(79, 68, 65))
    val jung = Jugador("Olivier Deman", Posicion.DEFENSOR, Habilidades(76, 72, 80))
    val friedl = Jugador("Marco Friedl", Posicion.DEFENSOR, Habilidades(78, 74, 75))
    val stark = Jugador("Niklas Stark", Posicion.DEFENSOR, Habilidades(80, 76, 72))
    val opitz = Jugador("Anthony Jung", Posicion.DEFENSOR, Habilidades(75, 73, 77))
    val lynen = Jugador("Jens Stage", Posicion.MEDIOCAMPISTA, Habilidades(79, 78, 76))
    val bittencourt = Jugador("Leonardo Bittencourt", Posicion.MEDIOCAMPISTA, Habilidades(80, 79, 81))
    val schmid = Jugador("Romano Schmid", Posicion.MEDIOCAMPISTA, Habilidades(78, 80, 77))
    val ducksch = Jugador("Marvin Ducksch", Posicion.DELANTERO, Habilidades(82, 78, 76))
    val borre = Jugador("Rafael Santos Borré", Posicion.DELANTERO, Habilidades(81, 77, 82))
    val kownacki = Jugador("Dawid Kownacki", Posicion.DELANTERO, Habilidades(78, 74, 75))

// FC AUGSBURGO (4-3-3)
    val dahmen = Jugador("Finn Dahmen", Posicion.ARQUERO, Habilidades(78, 67, 63))
    val gumny = Jugador("Robert Gumny", Posicion.DEFENSOR, Habilidades(77, 73, 79))
    val bauer = Jugador("Felix Uduokhai", Posicion.DEFENSOR, Habilidades(79, 75, 73))
    val gouweleeuw = Jugador("Jeffrey Gouweleeuw", Posicion.DEFENSOR, Habilidades(80, 76, 71))
    val iago = Jugador("Iago", Posicion.DEFENSOR, Habilidades(76, 74, 78))
    val rexhbecaj = Jugador("Lukas Rexhbecaj", Posicion.MEDIOCAMPISTA, Habilidades(78, 79, 75))
    val dorsch = Jugador("Niklas Dorsch", Posicion.MEDIOCAMPISTA, Habilidades(79, 80, 74))
    val maier = Jugador("Arne Maier", Posicion.MEDIOCAMPISTA, Habilidades(78, 81, 76))
    val vargas = Jugador("Ruben Vargas", Posicion.DELANTERO, Habilidades(80, 76, 84))
    val beljo = Jugador(" Dion Beljo", Posicion.DELANTERO, Habilidades(78, 74, 77))
    val demirovic = Jugador("Ermedin Demirović", Posicion.DELANTERO, Habilidades(81, 77, 79))

// MAINZ 05 (3-5-2)
    val zentner = Jugador("Robin Zentner", Posicion.ARQUERO, Habilidades(80, 69, 66))
    val hancheolsen = Jugador("Sepp van den Berg", Posicion.DEFENSOR, Habilidades(78, 74, 76))
    val bell = Jugador("Stefan Bell", Posicion.DEFENSOR, Habilidades(77, 73, 70))
    val caci = Jugador("Anthony Caci", Posicion.DEFENSOR, Habilidades(76, 75, 78))
    val daCosta = Jugador("Danny da Costa", Posicion.DEFENSOR, Habilidades(75, 72, 80))
    val barreiro = Jugador("Leandro Barreiro", Posicion.MEDIOCAMPISTA, Habilidades(78, 79, 76))
    val krauss = Jugador("Ludovit Reis", Posicion.MEDIOCAMPISTA, Habilidades(77, 78, 77))
    val amiri = Jugador("Nadiem Amiri", Posicion.MEDIOCAMPISTA, Habilidades(79, 81, 78))
    val gruda = Jugador("Brajan Gruda", Posicion.MEDIOCAMPISTA, Habilidades(78, 80, 82))
    val onisiwo = Jugador("Karim Onisiwo", Posicion.DELANTERO, Habilidades(79, 75, 81))
    val burgzorg = Jugador("Delano Burgzorg", Posicion.DELANTERO, Habilidades(78, 74, 83))

// UNION BERLIN (5-3-2)
    val ronnow = Jugador("Frederik Rønnow", Posicion.ARQUERO, Habilidades(82, 71, 67))
    val jaeckel = Jugador("Robin Knoche", Posicion.DEFENSOR, Habilidades(80, 76, 72))
    val leite = Jugador("Diogo Leite", Posicion.DEFENSOR, Habilidades(79, 75, 73))
    val doekhi = Jugador("Danilho Doekhi", Posicion.DEFENSOR, Habilidades(81, 77, 71))
    val gosens = Jugador("Robin Gosens", Posicion.DEFENSOR, Habilidades(82, 78, 80))
    val trimmel = Jugador("Christopher Trimmel", Posicion.DEFENSOR, Habilidades(77, 79, 75))
    val kral = Jugador("Alex Král", Posicion.MEDIOCAMPISTA, Habilidades(78, 80, 74))
    val haberer = Jugador("Janik Haberer", Posicion.MEDIOCAMPISTA, Habilidades(79, 78, 76))
    val schafer = Jugador("Rani Khedira", Posicion.MEDIOCAMPISTA, Habilidades(80, 79, 73))
    val behrens = Jugador("Kevin Behrens", Posicion.DELANTERO, Habilidades(78, 74, 75))
    val volland = Jugador("Lucas Tousart", Posicion.DELANTERO, Habilidades(79, 76, 77))

// SC FRIBURGO (4-4-2)
    val atubolu = Jugador("Noah Atubolu", Posicion.ARQUERO, Habilidades(79, 67, 65))
    val sildillia = Jugador("Kiliann Sildillia", Posicion.DEFENSOR, Habilidades(77, 73, 79))
    val ginter = Jugador("Matthias Ginter", Posicion.DEFENSOR, Habilidades(83, 78, 74))
    val lienhart = Jugador("Philipp Lienhart", Posicion.DEFENSOR, Habilidades(81, 76, 72))
    val gunter = Jugador("Christian Günter", Posicion.DEFENSOR, Habilidades(80, 79, 78))
    val eggestein = Jugador("Maximilian Eggestein", Posicion.MEDIOCAMPISTA, Habilidades(82, 81, 76))
    val hofler = Jugador("Nicolas Höfler", Posicion.MEDIOCAMPISTA, Habilidades(80, 79, 73))
    val weisshaupt = Jugador("Noah Weißhaupt", Posicion.MEDIOCAMPISTA, Habilidades(77, 76, 82))
    val donaz = Jugador("Yannik Keitel", Posicion.MEDIOCAMPISTA, Habilidades(76, 77, 78))
    val gregoritsch = Jugador("Michael Gregoritsch", Posicion.DELANTERO, Habilidades(80, 77, 75))
    val holer = Jugador("Lucas Höler", Posicion.DELANTERO, Habilidades(78, 75, 76))

// HAMBURGO SV (4-3-3)
    val heuerfernandes = Jugador("Daniel Heuer Fernandes", Posicion.ARQUERO, Habilidades(81, 69, 66))
    val hadzikadunic = Jugador("Anssi Suhonen", Posicion.DEFENSOR, Habilidades(76, 72, 77))
    val schonlau = Jugador("Sebastian Schonlau", Posicion.DEFENSOR, Habilidades(79, 75, 73))
    val vuskovic = Jugador("Mario Vušković", Posicion.DEFENSOR, Habilidades(77, 73, 71))
    val muheim = Jugador("Miro Muheim", Posicion.DEFENSOR, Habilidades(75, 74, 79))
    val benes = Jugador("Ludovit Reis", Posicion.MEDIOCAMPISTA, Habilidades(80, 79, 76))
    val meffert = Jugador("Jonas Meffert", Posicion.MEDIOCAMPISTA, Habilidades(78, 77, 74))
    val pherai = Jugador("László Bénes", Posicion.MEDIOCAMPISTA, Habilidades(79, 80, 77))
    val jatta = Jugador("Bakery Jatta", Posicion.DELANTERO, Habilidades(78, 74, 84))
    val glatzel = Jugador("Robert Glatzel", Posicion.DELANTERO, Habilidades(82, 78, 76))
    val dompe = Jugador("Jean-Luc Dompé", Posicion.DELANTERO, Habilidades(77, 75, 83))

    // BOCHUM (4-4-2)
    val riemann = Jugador("Manuel Riemann", Posicion.ARQUERO, Habilidades(78, 65, 62))
    val passlack = Jugador("Felix Passlack", Posicion.DEFENSOR, Habilidades(75, 71, 77))
    val masovic = Jugador("Erhan Mašović", Posicion.DEFENSOR, Habilidades(76, 72, 70))
    val ordets = Jugador("Ivan Ordets", Posicion.DEFENSOR, Habilidades(75, 71, 69))
    val wittek = Jugador("Christian Wittek", Posicion.DEFENSOR, Habilidades(74, 70, 75))
    val osterhage = Jugador("Patrick Osterhage", Posicion.MEDIOCAMPISTA, Habilidades(76, 75, 73))
    val losilla = Jugador("Anthony Losilla", Posicion.MEDIOCAMPISTA, Habilidades(77, 74, 72))
    val asano = Jugador("Takuma Asano", Posicion.DELANTERO, Habilidades(78, 72, 84))
    val stoeger = Jugador("Kevin Stöger", Posicion.MEDIOCAMPISTA, Habilidades(79, 78, 74))
    val antwiadjei = Jugador("Christopher Antwi-Adjei", Posicion.DELANTERO, Habilidades(76, 70, 83))
    val hofman = Jugador("Philipp Hofmann", Posicion.DELANTERO, Habilidades(77, 73, 71))

    // FC ST. PAULI (4-3-3) - Asumiendo ascenso
    val vasilj = Jugador("Nikola Vasilj", Posicion.ARQUERO, Habilidades(76, 64, 61))
    val burak = Jugador("Lars Ritzka", Posicion.DEFENSOR, Habilidades(74, 70, 76))
    val constable = Jugador("Connor Metcalfe", Posicion.DEFENSOR, Habilidades(75, 71, 72))
    val smith = Jugador("Adam Dźwigała", Posicion.DEFENSOR, Habilidades(73, 69, 71))
    val hartel = Jugador("Marcel Hartel", Posicion.DEFENSOR, Habilidades(75, 73, 74))
    val irvine = Jugador("Jackson Irvine", Posicion.MEDIOCAMPISTA, Habilidades(77, 76, 73))
    val kemlein = Jugador("Finn Ole Becker", Posicion.MEDIOCAMPISTA, Habilidades(74, 75, 72))
    val saeid = Jugador("Almond Yousef", Posicion.MEDIOCAMPISTA, Habilidades(73, 74, 75))
    val egestein = Jugador("Johannes Eggestein", Posicion.DELANTERO, Habilidades(78, 74, 79))
    val burgstaller = Jugador("Guido Burgstaller", Posicion.DELANTERO, Habilidades(77, 73, 75))
    val afolayan = Jugador("Oladapo Afolayan", Posicion.DELANTERO, Habilidades(76, 71, 82))


    // Añadir jugadores a los equipos alemanes
    bayernMunich.aniadirJugador(neuer)
    bayernMunich.aniadirJugador(davies)
    bayernMunich.aniadirJugador(deLigt)
    bayernMunich.aniadirJugador(kim)
    bayernMunich.aniadirJugador(mazraoui)
    bayernMunich.aniadirJugador(kimmich)
    bayernMunich.aniadirJugador(goretzka)
    bayernMunich.aniadirJugador(sane)
    bayernMunich.aniadirJugador(musiala)
    bayernMunich.aniadirJugador(coman)
    bayernMunich.aniadirJugador(kane)

    borussiaDortmund.aniadirJugador(kobel)
    borussiaDortmund.aniadirJugador(ryerson)
    borussiaDortmund.aniadirJugador(schlotterbeck)
    borussiaDortmund.aniadirJugador(hummels)
    borussiaDortmund.aniadirJugador(maatsen)
    borussiaDortmund.aniadirJugador(can)
    borussiaDortmund.aniadirJugador(brandt)
    borussiaDortmund.aniadirJugador(reus)
    borussiaDortmund.aniadirJugador(malen)
    borussiaDortmund.aniadirJugador(moukoko)
    borussiaDortmund.aniadirJugador(adeyemi)

    bayerLeverkusen.aniadirJugador(hradecky)
    bayerLeverkusen.aniadirJugador(tah)
    bayerLeverkusen.aniadirJugador(tapsoba)
    bayerLeverkusen.aniadirJugador(hincapie)
    bayerLeverkusen.aniadirJugador(frimpong)
    bayerLeverkusen.aniadirJugador(xhaka)
    bayerLeverkusen.aniadirJugador(palacios)
    bayerLeverkusen.aniadirJugador(grimaldo)
    bayerLeverkusen.aniadirJugador(hofmann)
    bayerLeverkusen.aniadirJugador(wirtz)
    bayerLeverkusen.aniadirJugador(boniface)

    rbLeipzig.aniadirJugador(gulacsi)
    rbLeipzig.aniadirJugador(henrichs)
    rbLeipzig.aniadirJugador(lukeba)
    rbLeipzig.aniadirJugador(simakan)
    rbLeipzig.aniadirJugador(raum)
    rbLeipzig.aniadirJugador(schlager)
    rbLeipzig.aniadirJugador(kampl)
    rbLeipzig.aniadirJugador(olmo)
    rbLeipzig.aniadirJugador(simons)
    rbLeipzig.aniadirJugador(sesko)
    rbLeipzig.aniadirJugador(openda)

    borussiaMonchengladbach.aniadirJugador(olschowsky)
    borussiaMonchengladbach.aniadirJugador(scally)
    borussiaMonchengladbach.aniadirJugador(mommel)
    borussiaMonchengladbach.aniadirJugador(friedrich)
    borussiaMonchengladbach.aniadirJugador(netz)
    borussiaMonchengladbach.aniadirJugador(kone)
    borussiaMonchengladbach.aniadirJugador(weigl)
    borussiaMonchengladbach.aniadirJugador(honorat)
    borussiaMonchengladbach.aniadirJugador(neuhaus)
    borussiaMonchengladbach.aniadirJugador(ngoumou)
    borussiaMonchengladbach.aniadirJugador(plea)

    eintrachtFrankfurt.aniadirJugador(trapp)
    eintrachtFrankfurt.aniadirJugador(tuta)
    eintrachtFrankfurt.aniadirJugador(koch)
    eintrachtFrankfurt.aniadirJugador(pacho)
    eintrachtFrankfurt.aniadirJugador(buta)
    eintrachtFrankfurt.aniadirJugador(skhiri)
    eintrachtFrankfurt.aniadirJugador(dinaebi)
    eintrachtFrankfurt.aniadirJugador(max)
    eintrachtFrankfurt.aniadirJugador(chaibi)
    eintrachtFrankfurt.aniadirJugador(marmoush)
    eintrachtFrankfurt.aniadirJugador(kalajdzic)

    vfbStuttgart.aniadirJugador(nubel)
    vfbStuttgart.aniadirJugador(vagnoman)
    vfbStuttgart.aniadirJugador(anton)
    vfbStuttgart.aniadirJugador(zagadou)
    vfbStuttgart.aniadirJugador(mittelstadt)
    vfbStuttgart.aniadirJugador(karazor)
    vfbStuttgart.aniadirJugador(stiller)
    vfbStuttgart.aniadirJugador(lewicki)
    vfbStuttgart.aniadirJugador(silas)
    vfbStuttgart.aniadirJugador(undav)
    vfbStuttgart.aniadirJugador(guirassy)

    vflWolfsburgo.aniadirJugador(casteels)
    vflWolfsburgo.aniadirJugador(baku)
    vflWolfsburgo.aniadirJugador(lacroix)
    vflWolfsburgo.aniadirJugador(jenz)
    vflWolfsburgo.aniadirJugador(maehle)
    vflWolfsburgo.aniadirJugador(svanberg)
    vflWolfsburgo.aniadirJugador(arnold)
    vflWolfsburgo.aniadirJugador(wimmer)
    vflWolfsburgo.aniadirJugador(majer)
    vflWolfsburgo.aniadirJugador(wind)
    vflWolfsburgo.aniadirJugador(amine)

    tsgHoffenheim.aniadirJugador(baumann)
    tsgHoffenheim.aniadirJugador(vogt)
    tsgHoffenheim.aniadirJugador(brooks)
    tsgHoffenheim.aniadirJugador(akpoguma)
    tsgHoffenheim.aniadirJugador(kaderabek)
    tsgHoffenheim.aniadirJugador(promel)
    tsgHoffenheim.aniadirJugador(stach)
    tsgHoffenheim.aniadirJugador(bebbou)
    tsgHoffenheim.aniadirJugador(kramaric)
    tsgHoffenheim.aniadirJugador(weghorst)
    tsgHoffenheim.aniadirJugador(berisha)

    fcKoln.aniadirJugador(schwabe)
    fcKoln.aniadirJugador(carstensen)
    fcKoln.aniadirJugador(hubers)
    fcKoln.aniadirJugador(heintz)
    fcKoln.aniadirJugador(paqarada)
    fcKoln.aniadirJugador(martel)
    fcKoln.aniadirJugador(ljubicic)
    fcKoln.aniadirJugador(maina)
    fcKoln.aniadirJugador(kainz)
    fcKoln.aniadirJugador(alidou)
    fcKoln.aniadirJugador(selke)

    werderBremen.aniadirJugador(zetterer)
    werderBremen.aniadirJugador(jung)
    werderBremen.aniadirJugador(friedl)
    werderBremen.aniadirJugador(stark)
    werderBremen.aniadirJugador(opitz)
    werderBremen.aniadirJugador(lynen)
    werderBremen.aniadirJugador(bittencourt)
    werderBremen.aniadirJugador(schmid)
    werderBremen.aniadirJugador(ducksch)
    werderBremen.aniadirJugador(borre)
    werderBremen.aniadirJugador(kownacki)

    fcAugsburg.aniadirJugador(dahmen)
    fcAugsburg.aniadirJugador(gumny)
    fcAugsburg.aniadirJugador(bauer)
    fcAugsburg.aniadirJugador(gouweleeuw)
    fcAugsburg.aniadirJugador(iago)
    fcAugsburg.aniadirJugador(rexhbecaj)
    fcAugsburg.aniadirJugador(dorsch)
    fcAugsburg.aniadirJugador(maier)
    fcAugsburg.aniadirJugador(vargas)
    fcAugsburg.aniadirJugador(beljo)
    fcAugsburg.aniadirJugador(demirovic)

    mainz05.aniadirJugador(zentner)
    mainz05.aniadirJugador(hancheolsen)
    mainz05.aniadirJugador(bell)
    mainz05.aniadirJugador(caci)
    mainz05.aniadirJugador(daCosta)
    mainz05.aniadirJugador(barreiro)
    mainz05.aniadirJugador(krauss)
    mainz05.aniadirJugador(amiri)
    mainz05.aniadirJugador(gruda)
    mainz05.aniadirJugador(onisiwo)
    mainz05.aniadirJugador(burgzorg)

    unionBerlin.aniadirJugador(ronnow)
    unionBerlin.aniadirJugador(jaeckel)
    unionBerlin.aniadirJugador(leite)
    unionBerlin.aniadirJugador(doekhi)
    unionBerlin.aniadirJugador(gosens)
    unionBerlin.aniadirJugador(trimmel)
    unionBerlin.aniadirJugador(kral)
    unionBerlin.aniadirJugador(haberer)
    unionBerlin.aniadirJugador(schafer)
    unionBerlin.aniadirJugador(behrens)
    unionBerlin.aniadirJugador(volland)

    scFreiburg.aniadirJugador(atubolu)
    scFreiburg.aniadirJugador(sildillia)
    scFreiburg.aniadirJugador(ginter)
    scFreiburg.aniadirJugador(lienhart)
    scFreiburg.aniadirJugador(gunter)
    scFreiburg.aniadirJugador(eggestein)
    scFreiburg.aniadirJugador(hofler)
    scFreiburg.aniadirJugador(weisshaupt)
    scFreiburg.aniadirJugador(donaz)
    scFreiburg.aniadirJugador(gregoritsch)
    scFreiburg.aniadirJugador(holer)

    hamburgosv.aniadirJugador(heuerfernandes)
    hamburgosv.aniadirJugador(hadzikadunic)
    hamburgosv.aniadirJugador(schonlau)
    hamburgosv.aniadirJugador(vuskovic)
    hamburgosv.aniadirJugador(muheim)
    hamburgosv.aniadirJugador(benes)
    hamburgosv.aniadirJugador(meffert)
    hamburgosv.aniadirJugador(pherai)
    hamburgosv.aniadirJugador(jatta)
    hamburgosv.aniadirJugador(glatzel)
    hamburgosv.aniadirJugador(dompe)

    bochum.aniadirJugador(riemann)
    bochum.aniadirJugador(passlack)
    bochum.aniadirJugador(masovic)
    bochum.aniadirJugador(ordets)
    bochum.aniadirJugador(wittek)
    bochum.aniadirJugador(osterhage)
    bochum.aniadirJugador(losilla)
    bochum.aniadirJugador(asano)
    bochum.aniadirJugador(stoeger)
    bochum.aniadirJugador(antwiadjei)
    bochum.aniadirJugador(hofman)

    stPauli.aniadirJugador(vasilj)
    stPauli.aniadirJugador(burak)
    stPauli.aniadirJugador(constable)
    stPauli.aniadirJugador(smith)
    stPauli.aniadirJugador(hartel)
    stPauli.aniadirJugador(irvine)
    stPauli.aniadirJugador(kemlein)
    stPauli.aniadirJugador(saeid)
    stPauli.aniadirJugador(egestein)
    stPauli.aniadirJugador(burgstaller)
    stPauli.aniadirJugador(afolayan)



    val equiposLiga = listOf(bayernMunich, borussiaDortmund, bayerLeverkusen, rbLeipzig,
        borussiaMonchengladbach, eintrachtFrankfurt, vfbStuttgart, vflWolfsburgo,
        tsgHoffenheim, fcKoln, werderBremen, fcAugsburg,
        mainz05, unionBerlin, scFreiburg, hamburgosv,
        bochum, stPauli)

    // Simular torneo
    val simulador = SimuladorTorneo(equiposLiga)
    val tablaFinal = simulador.simularTorneo()

    // Mostrar campeón
    val campeon = tablaFinal.maxByOrNull { it.value }
    println("\n¡CAMPEÓN: ${campeon?.key} con ${campeon?.value} puntos!")
}
